### ISSUE TITLE
Use HOCON for configs instead of YAML

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/geary#38]

**Comment by Derongan** [comment]
Do we have any real reason to do this rather than hocon is the newer cooler thing? AFAIK HOCON is much less adapted than yaml and json, so would be different/confusing to most users/contributors.

**Comment by 0ffz** [comment]
I think we get to do type mapping better instead of yaml's `!<namespace:key>` syntax, we should be able to write things out as though they're an actual map. Also you get way nicer support for making little templates, check out https://github.com/lightbend/config#uses-of-substitutions

**Comment by Derongan** [comment]
Isnt the <> stuff is just because of how spigot uses snake yaml I think. Only the ! matters for defining a tag which is essentially used as a hint about what the parser should do with this value. What is the equivalent in HOCON if I want to say serialize and deserialize a location and why is it better.

**Comment by 0ffz** [comment]
Abandoned as the default option because the HOCON serializer doesn't handle the `!<>` types, especially in maps well
